### ISSUE TITLE
i can't follow nijimiss.moe accounts

### ISSUE THREAD

**Issue by jiangshanghan** [TeamNijimiss/nijimiss_legacy#74]
## 💡 Summary

i want to use a mastodon account to follow another account which located in nijimiss.moe,but failed.

## 🥰 Expected Behavior

in the fediverse,mastodon and misskey shall be can connect with each other site.

## 🤬 Actual Behavior

hello nijimiss.moe admin! sorry for disturb.
I'm trying to follow an account located at nijimiss.moe with my mastodon account, but it's a complete failure. 
the mastodon administrator indicated that this might be a cross-site connection problem, but our  mastodon site had not set up a disconnect of Mastodon-to-Misskey.
I've tried exporting the follow list for my misskey account and importing it into my mastodon account, but the nijimiss.moe account is still unreadable.
How can I fix it? please.
thank you!

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:i m not sure,maybe 13
Your OS:windows and android
Your browser:firefox on pc and android

**Comment by nafu-at** [comment]
This issue has been addressed and resolved on an individual basis.

**Comment by jiangshanghan** [comment]
thank you Nafu san!

**Comment by jiangshanghan** [comment]
can i say..
i moved my mastodon account.. 
so in another instance i cant follow nijimiss accounts still.
for now i think i just use misskey account for that follow

**Comment by nafu-at** [comment]
Hello!
This instance prohibits access from the EU and some other countries for legal reasons.
Your follow request may have been rejected by this filter.
If you tell us the address of the server you belong to, we can bypass it.
