### ISSUE TITLE
絵文字一覧APIの一部のURLがアクセスできない

### ISSUE THREAD

**Issue by takke** [TeamNijimiss/nijimiss_legacy#78]
## 💡 Summary

Android用のアプリを作っている竹内と申します。

拙作のMisskey用アプリ(ZonePane 試作版)からにじみすの一部のカスタム絵文字が見られなくて困っております。

具体的には `:okaiki:` が Web からは 

```
https://nijimiss.moe/proxy/image.webp?url=https%3A%2F%2Fmedia.nijimiss.app%2Fnull%2F95a2da1b-db23-470b-93e7-9d01c23bda42.png&emoji=1
```

ですが絵文字一覧のAPIに載っているURLの

```
https://media.nijimiss.app/null/95a2da1b-db23-470b-93e7-9d01c23bda42.png
```

では 404 になってしまいます。絵文字によっては
```
https://media.nijimiss.app/null/212a6675-abb6-42a5-bcbe-b0b206f5d45b.png
```
のように問題なくアクセスできるものもあります。

アクセスできるようにしていただくか、APIのレスポンスにプロキシ経由のURLを記載していただきたいです。

いずれも難しいようであればアプリ側で変換しますのでご回答をお願いいたします。
(ユーザーさんが困っています)

(メモ) https://nijimiss.moe/notes/01GZTAM7WFK9WWG05288QVEYJE で問い合わせた件です。

## 🥰 Expected Behavior

https://media.nijimiss.app/null/95a2da1b-db23-470b-93e7-9d01c23bda42.png にアクセスできること。

または絵文字一覧のAPIから

https://nijimiss.moe/proxy/image.webp?url=https%3A%2F%2Fmedia.nijimiss.app%2Fnull%2F95a2da1b-db23-470b-93e7-9d01c23bda42.png&emoji=1

が返ってくること。

## 🤬 Actual Behavior

https://media.nijimiss.app/null/95a2da1b-db23-470b-93e7-9d01c23bda42.png にアクセスできない(404)

## 📝 Steps to Reproduce

1. https://media.nijimiss.app/null/95a2da1b-db23-470b-93e7-9d01c23bda42.png にブラウザでアクセスする。

## 📌 Environment

Misskey version: v13.11.3-nj
Your OS: Android
Your browser: (PC上のChromeにて確認)

アプリ自体はMisskey対応についてまだ試作段階となっており、https://fedibird.com/@takke/110337138378778354 などで随時配布しています。

**Comment by shiosyakeyakini-info** [comment]
こちらもクライアントアプリを同様に開発しており、同じ問題を抱えています。

また、クライアントアプリだけでなく、misskey.ioなど他のサーバーをChromeで閲覧している際ににじみすのノートやリアクションが連合で流れてくる場合でも、にじみすのカスタム絵文字が表示されないことが頻発しています。

クライアントアプリはクライアントアプリで対応できますが、にじみす以外のサーバーから連合する際のMisskey Webの表示についてはどうすることもできないので、解決していただけると幸いです。
